### ISSUE TITLE
Reports of 7800x and 7820x?

### ISSUE THREAD

**Issue by oscarbg** [Mysticial/Flops#17]
Hi seems Skylake-X Core i7 (6core 7800x and 8 core 7820x) releasing next week only have 1 FMA AVX512 unit vs   2 AVX512 units on Core i9 products (10 core 7900x right now)..
hope you can gather results on all this CPUs so we get clear response using your tool of max achievable FLOPS and the impact of AVX512 2nd unit..

**Comment by Mysticial** [comment]
Somebody on HWBOT ran this for me on the 7900X and the 7800X. And to my surprise, both of them appear to have full-throughput AVX512.

http://forum.hwbot.org/showthread.php?p=490233#post490233
http://www.overclock.net/t/1632638/just-a-heads-up-for-anyone-buying-x299-if-you-want-full-avx-capability-you-need-to-buy-the-7900x-and-up/20#post_26181442

But be aware that ES samples may not be representative of the final product.

**Comment by oscarbg** [comment]
thanks for the links!!

**Comment by oscarbg** [comment]
guess it's time to close..
