### ISSUE TITLE
Version 3 - Only x86 pre-compiled binaries ?

### ISSUE THREAD

**Issue by NikosDi** [Mysticial/Flops#25]
Hello.
It seems that inside this path version3/binaries-windows there are only x86 pre-compiled binaries.

Is it possible to add x64 too ?

TIA

**Comment by Mysticial** [comment]
Those binaries are x64. Not sure what you're looking at.

**Comment by NikosDi** [comment]
It seems like a false alarm, eventually.
I got a message that the executable could not run using Windows 11 due to incompatible "x86" error, but now I can execute it successfully.
TY
