### ISSUE TITLE
Windows binaries require VCOMP120.DLL

### ISSUE THREAD

**Issue by Diazonium** [Mysticial/Flops#5]
The windows binaries fail to start, complaining about a .dll missing.(VCOMP120.DLL)
I do not have MS Visual Studio installed. Maybe this is the source of this problem?

**Comment by Mysticial** [comment]
Ah yes. The binaries were compiled with Visual Studio 2013 which may use a newer version of the run-time libraries than what the OS has.

Try installing the redistributable package: http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by Diazonium** [comment]
I have installed the x64 version of the package you linked and now the benchmark runs fine.
Problem solved, thanks! :)
